(Generated by 3dpBurner Image2Gcode v1.1)
(@Aug/23/2016 20:09:59)
M42 P4 S0

(Header)
G0 X0 Y0
(Header end)
G90

G21

F1000

G0 Y33.75; Move to top left corner and begin box
G92 X0 Y33.75

M42 P4 S5
G0 X60
G0 Y0
G0 X0

G0 X0 Y50
G1
M42 P4 S0
G1 X0 G1 Y0 
M42 P4 S62
M42 P4 S0
(Footer)
G0 X0 Y0
(Footer end)
