Application: {Auto_Size: 'True', xsize: '446', ysize: '432'}
Gcode:
  Current: Wood
  Materials:
    Wood: {feedrate: '4000', high_power: '80', low_power: '0'}
  end_gcode: ''
  start_gcode: G28
Machine: {baud_rate: 250000, bed_length: '200', bed_width: '200', focus_distance: '8',
  laser_off_cmd: M42 P4 S0, laser_on_cmd: M42 P4 S0, laser_pwr_cmd: M42 P4 S, on_idle_delay: ''}
